### ISSUE TITLE
Je lijkt veel <div> te gebruiken

### ISSUE THREAD

**Issue by Patrickkhr** [DamianR2004/connect-your-tribe-profile-card#1]
https://github.com/DamianR2004/connect-your-tribe-profile-card/blob/626dca5ed8399aa3c7044cb93fece5fc8ac0039a/views/index.ejs#L13-L33

Je lijkt veel divjes te gebruiken maar er zijn ook andere elementen hiervoor.

Je kan kijken op mdn voor elementen om je html semantischer te maken!

bron: https://developer.mozilla.org/en-US/docs/Web/HTML/Element

**Comment by DamianR2004** [comment]
Ik heb ze helaas nodig, toch bedankt!
