### ISSUE TITLE
Hou een consistente css volgorde aan

### ISSUE THREAD

**Issue by MokhtarAkle** [DamianR2004/connect-your-tribe-profile-card#10]
https://github.com/DamianR2004/connect-your-tribe-profile-card/blob/626dca5ed8399aa3c7044cb93fece5fc8ac0039a/public/style/style.css#L74-L92

Probeer je CSS te schrijven gebaseerd op de volgorde waarin de elementen voorkomen in je HTML. Vervolgens kan je media queries en keyframes hieronder schrijven

**Comment by DamianR2004** [comment]
Is nagekeken, bedankt!
