### ISSUE TITLE
Je herhaald je zelf met codering

### ISSUE THREAD

**Issue by Vikkeyeftimov** [DamianR2004/connect-your-tribe-profile-card#11]
https://github.com/DamianR2004/connect-your-tribe-profile-card/blob/626dca5ed8399aa3c7044cb93fece5fc8ac0039a/public/style/style.css#L96-L107

Je codering wordt geherhaalt,

voor verbetering misschien een custom propertie gebruiken of de classlist bij css samenvoegen
https://www.bing.com/search?q=dry+css&qs=n&form=QBRE&sp=-1&ghc=1&lq=0&pq=dry+css&sc=11-7&sk=&cvid=E627EF7628DC44788E93478A70689FB6&ghsh=0&ghacc=0&ghpl=

**Comment by DamianR2004** [comment]
Gaat kapot als ik dit aanpas 😧

![](https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExZXZiMHRxY2x4cmtjN2xrZnV6bDFkaGQwODBkZmlucTJxbmVqZnZ2MCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xUA7b7eHmShdVRyvQc/giphy.gif)

**Comment by Vikkeyeftimov** [comment]
oei mijn fout wist dat niet volgende keer let ik daar beter voor op
