### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by Ronabundy1** [DamianR2004/connect-your-tribe-profile-card#5]
handige tip: probeer je in js meer comments te plaatsen 
Lijkt me ook duidelijk wat elke regel doet voor jezelf en voor anderen

https://github.com/DamianR2004/connect-your-tribe-profile-card/blob/626dca5ed8399aa3c7044cb93fece5fc8ac0039a/public/script/script.js#L1C1-L23C8

**Comment by DamianR2004** [comment]
Is opgelost, bedankt!
