### ISSUE TITLE
Code review 09/02 Gebruik data EJS, gebruik partials en gebruik public folder 👍 

### ISSUE THREAD

**Issue by MokhtarAkle** [DamianR2004/connect-your-tribe-profile-card#8]
- Data gebruik
Data wordt correct opgehaald en er is goed begrip van de werking van deze functie, 🔥 !

- Partials gebruik
Er is goed begrip van de functionaliteit van partials en deze worden ook correct toegepast. Tip: stop je <script> elementen in je footer partial om je bestand schoner te houden.

- Public folder gebruik
Er is goed begrip van de functionaliteit van de public map, hier zijn de images, script en stylesheet uit opgehaald. Snapt het verschil tussen statische client side rendering en server side rendering.

**Comment by DamianR2004** [comment]
Ik heb mijn script verplaatst, bedankt voor de feedback!
