### ISSUE TITLE
Probeer SVG elementen te optimaliseren

### ISSUE THREAD

**Issue by MokhtarAkle** [DamianR2004/connect-your-tribe-profile-card#9]
https://github.com/DamianR2004/connect-your-tribe-profile-card/blob/626dca5ed8399aa3c7044cb93fece5fc8ac0039a/views/index.ejs#L14

Je kan je SVG elementen korter en meer geoptimaliseerd maken via de volgende service: https://jakearchibald.github.io/svgomg/
Probeer hier gebruik van te maken voor schonere bestanden en code,

**Comment by DamianR2004** [comment]
Bedankt voor deze tip! Is opgelost
